# Generated by Django 3.2.18 on 2023-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigerim', '0002_auto_20230408_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigerim',
            name='price',
            field=models.BigIntegerField(default=1000),
        ),
    ]
