# Generated by Django 3.2.18 on 2023-04-08 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aigerim', '0003_aigerim_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigerim',
            options={'ordering': ['title'], 'verbose_name': 'Известные Пандоры', 'verbose_name_plural': 'Известные Пандоры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='aigerim',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aigerim.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='aigerim',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='aigerim',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='aigerim',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='ФОто'),
        ),
        migrations.AlterField(
            model_name='aigerim',
            name='price',
            field=models.BigIntegerField(default=1000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='aigerim',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
    ]
